# application.properties - ms-ventas
# Configuración del Microservicio de Ventas para BookPoint Chile
# Arquitecto de Software: Antigravity

# Puerto del Servidor local
server.port=8081

# Nombre de la aplicación en Spring Boot / Eureka
spring.application.name=ms-ventas

# Configuración de Base de Datos MySQL (Esquema: bookpoint_ventas)
spring.datasource.url=jdbc:mysql://localhost:3306/bookpoint_ventas?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# Configuración JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Registro y Descubrimiento con Eureka (Comentado o desactivado por defecto en local si no está activo el servidor Eureka)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.enabled=false

# Configuración del Cliente Feign del ms-inventario
app.feign.ms-inventario.url=http://localhost:8082
feign.client.config.default.connect-timeout=5000
feign.client.config.default.read-timeout=5000

# Habilitar logging del nivel INFO para trazas personalizadas en Service
logging.level.cl.bookpointchile.ventas=INFO
